### ISSUE TITLE
Expired Certificate on Website

### ISSUE THREAD

**Issue by bramus** [revoltphp/event-loop#38]
When visiting revolt.run, I'm greeted with a certificate expiration error.

![image](https://user-images.githubusercontent.com/213073/148902918-138ff6c3-fd5b-40ed-8432-9628603c65c0.png)

**Comment by kelunik** [comment]
We're aware of that. Unfortunately, it's a bug in Github Pages certificate issuance. We hit that issue with the initial certificate, and hit it again now. Github's support needs to manually bug the engineering team and the ticket has been open for 9 days already.

If the problem persists, we need to look for another solution to provide HTTPS.

**Comment by WyriHaximus** [comment]
We could put cloudflare in front of it to mitigate this. Let me see how we set up reactphp.org, but I'm pretty sure we did exactly that

**Comment by kelunik** [comment]
Yes, we also do that for amphp.org, so it's definitely an option. I've asked GitHub about the underlying issue, let's see what they respond. There's been an update to the ticket, but it's not a comment I can see, so I assume it's some internal comment or something.

**Comment by kelunik** [comment]
Here's what happened: There's been a wrong `NS` record for `revolt.run` pointing to itself rather than the correct nameservers, while the parent zone had the correct nameservers:

```
dig +trace +add revolt.run NS
...
revolt.run.		3600	IN	NS	mercury.negativeion.net.
revolt.run.		3600	IN	NS	carbon.negativeion.net.
revolt.run.		3600	IN	NS	sodium.negativeion.net.
...
;; Received 619 bytes from 2a01:8840:fa::40#53(v0n3.nic.run) in 348 ms

revolt.run.		10800	IN	NS	revolt.run.
revolt.run.		10800	IN	A	185.199.110.153
revolt.run.		10800	IN	A	185.199.111.153
revolt.run.		10800	IN	A	185.199.108.153
revolt.run.		10800	IN	A	185.199.109.153
;; Received 117 bytes from 199.38.81.196#53(sodium.negativeion.net) in 276 ms
```

If the resolver tried to use the `NS` record of `revolt.run` from the local zone instead of the parent zone, it tried to use one of GitHub's servers as DNS server, which obviously didn't work.

We've fixed the local zone now to report the correct DNS servers:

```
revolt.run.		10800	IN	NS	mercury.negativeion.net.
revolt.run.		10800	IN	NS	sodium.negativeion.net.
revolt.run.		10800	IN	NS	carbon.negativeion.net.
carbon.negativeion.net.	10800	IN	A	199.38.81.193
sodium.negativeion.net.	10800	IN	A	199.38.81.196
mercury.negativeion.net. 10800	IN	A	199.38.81.6
```

So this has been a configuration issue on our side. I visited the GitHub Pages settings site and it triggered the issuance, so everything seems to be working now. \o/
